### ISSUE TITLE
[PE-D] Not Mentioned formatting in the user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#257]
![image.png](https://raw.githubusercontent.com/CommanderW324/ped/main/files/853127fd-9559-415f-b55e-a3d8e050234b.png)
For example the student address contains r/ in it then it does not work. Maybe mention it in the user guide ?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: CommanderW324/ped#5

**Comment by michael-lee-sk** [comment]
are there any addresses with r/ inside haha
