### ISSUE TITLE
[PE-D] UG info slightly incorrect

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#258]
Might want to change UG for adding lesson, since d/wed also works

![image.png](https://raw.githubusercontent.com/kevin9foong/ped/main/files/170f1c53-453e-458d-a498-533029f42fc0.png)

eg, add-l s/12 g/P1 d/wed t/0000 c/0

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: kevin9foong/ped#9

**Comment by muhammad-khair** [comment]
Solution:
- Update UG
