### ISSUE TITLE
[PE-D] Minor bug in the add command input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#259]
It is possible to enter clearly invalid email addresses such as jd@gmail.com.this.that.this.that.this.that using the add command. 

![Screenshot 2021-10-29 at 5.00.03 PM.png](https://raw.githubusercontent.com/tsm1820/ped/main/files/6badc814-e75a-4009-805b-4ba757beb984.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: tsm1820/ped#14

**Comment by muhammad-khair** [comment]
Solution:
- Add in FAQ and add student command about this issue
- Also include how it is the CSO's job to ensure its correct, else they can use the edit command to rectify this issue
