### ISSUE TITLE
[PE-D] Does not specify why a user cannot be enrolled

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#261]
![image.png](https://raw.githubusercontent.com/kevin9foong/ped/main/files/10519c6f-8845-435b-8811-5825bfd289b7.png)

There are 2 cases: 
- when grades dont match 
- when timings collide 

but the app doesnt indicate which case it is.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: kevin9foong/ped#10

**Comment by muhammad-khair** [comment]
Solution:
- Abstract/Refactor messages and deal with proper ordering of message output logic
