### ISSUE TITLE
[PE-D] Data saved at location, file not found but data still presented

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#265]
![Screenshot 2021-10-29 at 5.12.42 PM.png](https://raw.githubusercontent.com/benluiwj/ped/main/files/576c2c4f-e8e4-442f-a3dd-8ec7e0f66b18.png)

Notice that the location of the file does not seem to be found in data folder. Additionally, no new file is created.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: benluiwj/ped#5

**Comment by muhammad-khair** [comment]
Not valid, read our UG for more information about this.
