### ISSUE TITLE
[PE-D] Sample add command doesn't work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#268]
![Screenshot 2021-10-29 at 5.20.31 PM.png](https://raw.githubusercontent.com/benluiwj/ped/main/files/d8e1f6d8-3f13-4903-b012-7de705a884d5.png)

![Screenshot 2021-10-29 at 5.20.58 PM.png](https://raw.githubusercontent.com/benluiwj/ped/main/files/23e66ded-f9dc-4f6c-be49-82c91aade4aa.png)

Sample add command provided in command summary doesn't work (as seen in the second screenshot)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: benluiwj/ped#6

**Comment by muhammad-khair** [comment]
Solution:
- Add a S5
- Update UG
