### ISSUE TITLE
[PE-D] Remarks with spaces don't work in Edit Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#270]
![Screenshot 2021-10-29 at 5.26.40 PM.png](https://raw.githubusercontent.com/benluiwj/ped/main/files/287a993a-1545-4a60-8358-445c943d0887.png)

Input does not work even when remark is fewer than 25 characters long

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: benluiwj/ped#8

**Comment by muhammad-khair** [comment]
See #269
