### ISSUE TITLE
[PE-D] Unclear note about command format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#271]
![Screenshot 2021-10-29 at 5.36.41 PM.png](https://raw.githubusercontent.com/benluiwj/ped/main/files/57fab589-3701-484e-a770-da82f3b2d2fc.png)

Can be used as a blank space seems quite confusing as to what is trying to be said here

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: benluiwj/ped#9

**Comment by muhammad-khair** [comment]
Solution:
- Change wording (you can choose not to add remarks if you wish)
