### ISSUE TITLE
[PE-D] Suggestions

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-4/tp#272]
Maybe it would be good to add an edit command for lessons as well, since it can be quite troublesome to add a new lesson from scratch if we want to change a certain aspect of it like time or price.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: benluiwj/ped#10

**Comment by muhammad-khair** [comment]
Solution:
- Add as FAQ (and workaround, delete-l and then add-l)
- Add that it can be an upcoming feature
